name: Build

#ide kell felsorolni az eventeket
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    
jobs:
  build:
  #ez gyakorlatilag egy docker image 
    runs-on: ubuntu-latest

    #steppek, amik a containerben lefutnak
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          #cache beallitas
          cache: 'maven' #mavent irod, akkor tudja melyiknek kell a cahcba berakni
      - name: Build with Maven
        run: ./mvnw -B package # -B: batch mode, hogy ne kérdezzen semmit

  integration-tests:
    runs-on: ubuntu-latest
    needs: build #ez a job csak akkor fut le, ha a build sikeres volt

    steps:
      - run: echo "Run integration tests"
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          #cache beallitas
          cache: 'maven' #mavent irod, akkor tudja melyiknek kell a cahcba berakni
      - name: Build with Maven
        run: ./mvnw -B verify
      
  build-image:
    runs-on: ubuntu-latest
    needs: build #ez a job csak akkor fut le, ha a build sikeres volt

    steps:
      - run: echo "Build Docker images"
      
  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - run: echo "Deploy application here"   
